name: Logic Test
on: pull_request

jobs:
  check-math:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Needed to fetch the script
      
      - name: Run the "Test"
        run: node test/ci_test.js
