name: Logic Test
on: pull_request  # Triggers when you open a PR

jobs:
  check-math:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Needed to fetch the script
      
      - name: Run the "Test"
        run: test/node ci_test.js
